version: '2'
services:
  proxy:
    restart: on-failure
    image: schmunk42/nginx-proxy:0.4.0
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443

